#%RAML 1.0
title: Autonomus 2.0
version: v1
baseUri: http://develop-dot-autonomus.appspot.com/
mediaType: application/json
description: Our project for web technologies 2019
traits: 
  hasHeaders: 
    headers: 
      Authorization: 
        displayName: Authorization
        description: Basic authentication base 64 encoded string
        type: string
        required: true
      Content-type: 
        displayName: Content-type
        description: either xml or json
        type: string
        required: false

/login:
  displayName: Login
  post:
    is: ["hasHeaders"]
    description: Login for user or admin
    queryParameters:
      username:
        displayName: email
        type: string
        description: Email of an existing user
        example: ifjkghd@gmail.com
        required: true
      password:
        displayName: password
        type: string
        description: Password of the user willing to log in
        example: anaremere1
        required: true
    body:
      application/json:
         type: |
      {
	"type": "object",
        "required": true,
        "properties": {
	        "email": "string",       
		"password": "string",
        }
      }
    example: |
      {
	"email": "irina453orufs@gmail.com",
 	"password": "irin349824"
      }
    responses:
        200:
          body:
            application/json:
              example: |
                {
                  "data": {
                    "user_id": "ag1lfmZpaS1zdHVkZW50chMLEgZDb3Vyc2UYgICAhOzMwAgMogELZGV2ZWxvcG1lbnQ",
                    "access_token": "eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJ1c2VySWQiOiJiMDhmODZhZi0zNWRhLTQ4ZjItOGZhYi1jZWYzOTA0NjYwYmQifQ.-xN_h82PHVTCMA9vdoHrcZxH-x5mb11y1537t3rGzcM"
                  },
                  "success": true,
                  "status": 200
                }
        404:
          body:
            application/json:
              example: |
                {
                  "data": {
                    "user_id": ""
                  },
                  "success": false,
                  "status": 404
                }
	400:
	  body:
	    application/json:
 	      example: {
    		"status": "400",
  		"message": "Please specify email and password",
    		"payload": null
		}
      
/register:
  displayName: Register
  post:
    description: Register new user
    queryParameters:
      username:
        displayName: Username
        type: string
        description: Username of user willing to register
        example: AndreeaB
        required: true
      password:
        displayName: Password
        type: string
        description: Password of user willing to register
        example: anaaremare1
        required: true
        minLength: 8
      email:
        displayName: Email
        type: string
        description: Email of user willing to register
        example: andreeab@gmail.com
        required: true
    responses:
        201:
          body:
            application/json:
              example: |
                {
                  "data": {
                    "user_id": "ag1lfmZpaS1zdHVkZW50chMLEgZDb3Vyc2UYgICAhOzMwAgMogELZGV2ZWxvcG1lbnQ"
                  },
                  "success": true,
                  "status": 201
                }
        400:
          body:
            application/json:
              example: |
                {
                  "data": {
                    "user_id": ""
                  },
                  "success": false,
                  "status": 400
                }
                
/users:
  /{user_id}/{event_id}:
    displayName: User events
    uriParameters:
      user_id:
        displayName: User Id
        example: ag1lfmZpaS1zdHVkZW50chMLEgZDb3Vyc2UYgICAhOzMwAgMogELZGV2ZWxvcG1lbnQ
        description: Url safe for user
      event_id:
        displayName: Event Id
        example: ag1lfmZpaS1zdHVkZW50chMLEgZDb3Vyc2UYgICAhOzMwAgMogELZGV2ZWxvcG1lbnQ
        description: Url safe for event
    put:
      description: Adds new event to going list of given user
      queryParameters: 
        access_token:
          displayName: Access Token
          type: string
          description: Token to authorize the operation
          required: true
          example: eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJ1c2VySWQiOiJiMDhmODZhZi0zNWRhLTQ4ZjItOGZhYi1jZWYzOTA0NjYwYmQifQ.-xN_h82PHVTCMA9vdoHrcZxH-x5mb11y1537t3rGzcM
      responses:
        201:
          body:
            application/json:
              example: |
                {
                  "success": true,
                  "status": 201
                }
        404:
          body:
            application/json:
              example: |
                {
                  "success": false,
                  "status": 404
                }
        401:
          body:
            application/json:
              example: |
                {
                  "success": false,
                  "status": 401
                }
/events:
  displayName: Events
  get:
    description: Retrieves all events
    queryParameters:
      access_token:
          displayName: Access Token
          type: string
          description: Token to authorize the operation
          required: true
          example: eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJ1c2VySWQiOiJiMDhmODZhZi0zNWRhLTQ4ZjItOGZhYi1jZWYzOTA0NjYwYmQifQ.-xN_h82PHVTCMA9vdoHrcZxH-x5mb11y1537t3rGzcM
    responses:
      200:
        body:
          application/json:
            example: |
              {
                "events": [
                {
                  "event_id": "ag1lfmZpaS1zdHVkZW50chMLEgZDb3Vyc2UYgICAhOzMwAgMogELZGV2ZWxvcG1lbnQ",
                  "title": "Stiff: The Curious Lives of Human Cadavers",
                  "description": null,
                  "location": "Fab Lab",
                  "date": "05/21/2019 8:00PM",
                  "price": "10 RON",
                  "image_link": "https://www.pexhttps://images.pexels.com/photos/67636/rose-blue-flower-rose-blooms-67636.jpeg",
                  "capacity": 200,
                  "tags": ["Web", "Public Speaking", "Flying"]
                },
                {
                  "event_id": "ag1lfmZpaS1zdHVkZW50chMLEgZDb3Vyc2UYgICAhOzMwAgMogELZGV2ZWxvcG1lbnQ",
                  "title": "Stiff: The Curious Lives of Human Cadavers",
                  "description": null,
                  "location": "Fab Lab",
                  "date": "05/21/2019 8:00PM",
                  "price": "10 RON",
                  "image_link": "https://www.pexhttps://images.pexels.com/photos/67636/rose-blue-flower-rose-blooms-67636.jpeg",
                  "capacity": 100,
                  "tags": ["Web", "Public Speaking", "Flying"]
                }],
                "success": true,
                "status": 200
              }
      204:
        body:
          application/json:
            example: |
              {
                "events": [],
                "success": true,
                "status": 204
              }
      401:
        body:
          application/json:
            example: |
              {
                "events": [],
                "success": false,
                "status": 401
              }
  /{event_id}/{field_name}:
    uriParameters:
      field_name:
        displayName: Field name
        example: title
        description: Name of the field being modified
      event_id:
        displayName: Event Id
        example: ag1lfmZpaS1zdHVkZW50chMLEgZDb3Vyc2UYgICAhOzMwAgMogELZGV2ZWxvcG1lbnQ
        description: Url safe for event
    put:
      description: Updates data stored in given field for the given event
      queryParameters:
        access_token:
          displayName: Access Token
          type: string
          description: Token to authorize the operation
          required: true
          example: eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJ1c2VySWQiOiJiMDhmODZhZi0zNWRhLTQ4ZjItOGZhYi1jZWYzOTA0NjYwYmQifQ.-xN_h82PHVTCMA9vdoHrcZxH-x5mb11y1537t3rGzcM
        modification:
          displayName: Modification
          type: string
          description: Modification that is to be applied to the given field
          example: This is a meetup event!
          required: true
      responses:
        200:
          body:
            application/json:
              example: |
                {
                  "success": true,
                  "status": 200
                }
        404:
          body:
            application/json:
              example: |
                {
                  "success": false,
                  "status": 404
                }
        401:
          body:
            application/json:
              example: |
                {
                  "success": false,
                  "status": 401
                }
  /{tag_id}:
    uriParameters:
      tag_id:
        displayName: Tag Id
        example: ag1lfmZpaS1zdHVkZW50chMLEgZDb3Vyc2UYgICAhOzMwAgMogELZGV2ZWxvcG1lbnQ
        description: Url safe for tag
    get:
      description: Retrieves all events with given tag
      queryParameters: 
        access_token:
          displayName: Access Token
          type: string
          description: Token to authorize the operation
          required: true
          example: eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJ1c2VySWQiOiJiMDhmODZhZi0zNWRhLTQ4ZjItOGZhYi1jZWYzOTA0NjYwYmQifQ.-xN_h82PHVTCMA9vdoHrcZxH-x5mb11y1537t3rGzcM
      responses:
        200:
          body:
            application/json:
              example: |
                {
                  "events": [
                  {
                    "event_id": "ag1lfmZpaS1zdHVkZW50chMLEgZDb3Vyc2UYgICAhOzMwAgMogELZGV2ZWxvcG1lbnQ",
                    "title": "Stiff: The Curious Lives of Human Cadavers",
                    "description": null,
                    "location": "Fab Lab",
                    "date": "05/21/2019 8:00PM",
                    "price": "10 RON",
                    "image_link": "https://www.pexhttps://images.pexels.com/photos/67636/rose-blue-flower-rose-blooms-67636.jpeg",
                    "capacity": 200,
                    "tags": ["Web", "Public Speaking", "Flying"]
                  },
                  {
                    "event_id": "ag1lfmZpaS1zdHVkZW50chMLEgZDb3Vyc2UYgICAhOzMwAgMogELZGV2ZWxvcG1lbnQ",
                    "title": "Stiff: The Curious Lives of Human Cadavers",
                    "description": null,
                    "location": "Fab Lab",
                    "date": "05/21/2019 8:00PM",
                    "price": "10 RON",
                    "image_link": "https://www.pexhttps://images.pexels.com/photos/67636/rose-blue-flower-rose-blooms-67636.jpeg",
                    "capacity": 100,
                    "tags": ["Web", "Public Speaking", "Flying"]
                  }],
                  "success": true,
                  "status": 200
                }
        204:
          body:
            application/json:
              example: |
                {
                  "events": [],
                  "success": true,
                  "status": 204
                }
        401:
          body:
            application/json:
              example: |
                {
                  "events": [],
                  "success": false,
                  "status": 401
                }
/requests:
  displayName: requests
  get:
    description: Retrieves all requests
    queryParameters: 
      access_token:
          displayName: Access Token
          type: string
          description: Token to authorize the operation
          required: true
          example: eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJ1c2VySWQiOiJiMDhmODZhZi0zNWRhLTQ4ZjItOGZhYi1jZWYzOTA0NjYwYmQifQ.-xN_h82PHVTCMA9vdoHrcZxH-x5mb11y1537t3rGzcM
    responses:
      200:
        body:
          application/json:
            example: |
              {
                "requests": [
                {
                  "request_id": "ag1lfmZpaS1zdHVkZW50chMLEgZDb3Vyc2UYgICAhOzMwAgMogELZGV2ZWxvcG1lbnQ",
                  "field_name": "title",
                  "modification": "A new title"
                },
                {
                  "request_id": "ag1lfmZpaS1zdHVkZW50chMLEgZDb3Vyc2UYgICAhOzMwAgMogELZGV2ZWxvcG1lbnQ",
                  "field_name": "price",
                  "modification": "20 RON"
                }],
                "success": true,
                "status": 200
              }
      204:
        body:
          application/json:
            example: |
              {
                "requests": [],
                "success": true,
                "status": 204
              }
      401:
        body:
          application/json:
            example: |
              {
                "requests": [],
                "success": false,
                "status": 401
              }
  /{event_id}:
    uriParameters:
      event_id:
        displayName: Event Id
        example: ag1lfmZpaS1zdHVkZW50chMLEgZDb3Vyc2UYgICAhOzMwAgMogELZGV2ZWxvcG1lbnQ
        description: Url safe for event
    post:
      description: Inserts new change request
      queryParameters:
        username:
          displayName: Username
          type: string
          description: Username of user submitting the change
          example: AndreeaB
          required: true
        field_name:
          displayName: Field name
          type: string
          description: Field of the event to be updated
          example: title
          required: true
        modification:
          displayName: Modification
          type: string
          description: Modification that is to be applied to the given field
          example: This is the new title!
          required: true
        access_token:
          displayName: Access Token
          type: string
          description: Token to authorize the operation
          required: true
          example: eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJ1c2VySWQiOiJiMDhmODZhZi0zNWRhLTQ4ZjItOGZhYi1jZWYzOTA0NjYwYmQifQ.-xN_h82PHVTCMA9vdoHrcZxH-x5mb11y1537t3rGzcM
      responses:
        201:
          body:
            application/json:
              example: |
                {
                  "data": 
                  {
                    "request_id": "ag1lfmZpaS1zdHVkZW50chMLEgZDb3Vyc2UYgICAhOzMwAgMogELZGV2ZWxvcG1lbnQ"
                  },
                  "success": true,
                  "status": 201
                }
        401:
          body:
            application/json:
              example: |
                {
                  "data": null,
                  "success": false,
                  "status": 401
                }  
    put:
      description: Accepts or denies a change requests
      queryParameters:
        state:
          displayName: State
          example: Accepted
          enum:
            - Accepted
            - Denied
          description: The new state of the request
        access_token:
          displayName: Access Token
          type: string
          description: Token to authorize the operation
          required: true
          example: eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJ1c2VySWQiOiJiMDhmODZhZi0zNWRhLTQ4ZjItOGZhYi1jZWYzOTA0NjYwYmQifQ.-xN_h82PHVTCMA9vdoHrcZxH-x5mb11y1537t3rGzcM
      responses:
        200:
          body:
            application/json:
              example: |
                {
                  "data": 
                  {
                    "request_id": "ag1lfmZpaS1zdHVkZW50chMLEgZDb3Vyc2UYgICAhOzMwAgMogELZGV2ZWxvcG1lbnQ"
                  },
                  "success": true,
                  "status": 200
                }
        404:
          body:
            application/json:
              example: |
                {
                  "data": null,
                  "success": false,
                  "status": 404
                }
        401:
          body:
            application/json:
              example: |
                {
                  "data": null,
                  "success": false,
                  "status": 401
                }  
    
/tags:
  displayName: tags
  get:
    description: Retrieves all tags
    queryParameters: 
      access_token:
          displayName: Access Token
          type: string
          description: Token to authorize the operation
          required: true
          example: eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJ1c2VySWQiOiJiMDhmODZhZi0zNWRhLTQ4ZjItOGZhYi1jZWYzOTA0NjYwYmQifQ.-xN_h82PHVTCMA9vdoHrcZxH-x5mb11y1537t3rGzcM
    responses:
      200:
        body:
          application/json:
            example: |
              {
                "tags": [
                {
                  "tag_id": "ag1lfmZpaS1zdHVkZW50chMLEgZDb3Vyc2UYgICAhOzMwAgMogELZGV2ZWxvcG1lbnQ",
                  "tag_name": "Web"          
                },
                {
                  "tag_id": "ag1lfmZpaS1zdHVkZW50chMLEgZDb3Vyc2UYgICAhOzMwAgMogELZGV2ZWxvcG1lbnQ",
                  "tag_name": "AI"
               }],
                "success": true,
                "status": 200
              }
      204:
        body:
          application/json:
            example: |
              {
                "tags": [],
                "success": true,
                "status": 204
              }
      401:
        body:
          application/json:
            example: |
              {
                "tags": null,
                "success": false,
                "status": 401
              }
  post:
    description: Inserts new tag
    queryParameters: 
      tag_name:
        displayName: Tag Name
        type: string
        description: The tag being added to the tags list
        example: Web
        required: true
      access_token:
          displayName: Access Token
          type: string
          description: Token to authorize the operation
          required: true
          example: eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJ1c2VySWQiOiJiMDhmODZhZi0zNWRhLTQ4ZjItOGZhYi1jZWYzOTA0NjYwYmQifQ.-xN_h82PHVTCMA9vdoHrcZxH-x5mb11y1537t3rGzcM
    responses:
        201:
          body:
            application/json:
              example: |
                {
                  "data": 
                  {
                    "tag_id": "ag1lfmZpaS1zdHVkZW50chMLEgZDb3Vyc2UYgICAhOzMwAgMogELZGV2ZWxvcG1lbnQ"
                  },
                  "success": true,
                  "status": 201
                }
        401:
          body:
            application/json:
              example: |
                {
                  "data": null,
                  "success": false,
                  "status": 401
                }
  /{tag_id}/{user_id}:
    put:
      description: Adds given tag to the given user
      queryParameters: 
        access_token:
          displayName: Access Token
          type: string
          description: Token to authorize the operation
          required: true
          example: eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJ1c2VySWQiOiJiMDhmODZhZi0zNWRhLTQ4ZjItOGZhYi1jZWYzOTA0NjYwYmQifQ.-xN_h82PHVTCMA9vdoHrcZxH-x5mb11y1537t3rGzcM
      responses:
        200:
          body:
            application/json:
              example: |
                {
                  "data": 
                  {
                    "tag_id": "ag1lfmZpaS1zdHVkZW50chMLEgZDb3Vyc2UYgICAhOzMwAgMogELZGV2ZWxvcG1lbnQ"
                  },
                  "success": true,
                  "status": 200
                }
        404:
          body:
            application/json:
              example: |
                {
                  "data": null,
                  "success": false,
                  "status": 404
                }
        401:
          body:
            application/json:
              example: |
                {
                  "data": null,
                  "success": false,
                  "status": 401
                }
/links:
  displayName: links
  get:
    description: Retrieves all links
    queryParameters: 
      access_token:
          displayName: Access Token
          type: string
          description: Token to authorize the operation
          required: true
          example: eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJ1c2VySWQiOiJiMDhmODZhZi0zNWRhLTQ4ZjItOGZhYi1jZWYzOTA0NjYwYmQifQ.-xN_h82PHVTCMA9vdoHrcZxH-x5mb11y1537t3rGzcM
    responses:
      200:
        body:
          application/json:
            example: |
              {
                "links": [
                {
                  "link_id": "ag1lfmZpaS1zdHVkZW50chMLEgZDb3Vyc2UYgICAhOzMwAgMogELZGV2ZWxvcG1lbnQ",
                  "tag_name": "Web"          
                },
                {
                  "link_id": "ag1lfmZpaS1zdHVkZW50chMLEgZDb3Vyc2UYgICAhOzMwAgMogELZGV2ZWxvcG1lbnQ",
                  "tag_name": "AI"
               }],
                "success": true,
                "status": 200
              }
      204:
        body:
          application/json:
            example: |
              {
                "links": [],
                "success": true,
                "status": 204
              }
      401:
        body:
          application/json:
            example: |
              {
                "links": null,
                "success": false,
                "status": 401
              }
  post:
    description: Inserts new link
    queryParameters: 
      link:
        displayName: Link
        description: New link to be crawled
        example: https://facebook.com/FabLabIasi
        required: true
        type: string
      access_token:
          displayName: Access Token
          type: string
          description: Token to authorize the operation
          required: true
          example: eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJ1c2VySWQiOiJiMDhmODZhZi0zNWRhLTQ4ZjItOGZhYi1jZWYzOTA0NjYwYmQifQ.-xN_h82PHVTCMA9vdoHrcZxH-x5mb11y1537t3rGzcM
    responses:
        201:
          body:
            application/json:
              example: |
                {
                  "data": 
                  {
                    "link_id": "ag1lfmZpaS1zdHVkZW50chMLEgZDb3Vyc2UYgICAhOzMwAgMogELZGV2ZWxvcG1lbnQ"
                  },
                  "success": true,
                  "status": 201
                }
        401:
          body:
            application/json:
              example: |
                {
                  "data": null,
                  "success": false,
                  "status": 401
                }
  /{link_id}:
    delete:
      description: Removes a link
      queryParameters: 
        access_token:
          displayName: Access Token
          type: string
          description: Token to authorize the operation
          required: true
          example: eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJ1c2VySWQiOiJiMDhmODZhZi0zNWRhLTQ4ZjItOGZhYi1jZWYzOTA0NjYwYmQifQ.-xN_h82PHVTCMA9vdoHrcZxH-x5mb11y1537t3rGzcM
      responses:
        201:
          body:
            application/json:
              example: |
                {
                  "data": 
                  {
                    "tag_id": "ag1lfmZpaS1zdHVkZW50chMLEgZDb3Vyc2UYgICAhOzMwAgMogELZGV2ZWxvcG1lbnQ"
                  },
                  "success": true,
                  "status": 201
                }
        404:
          body:
            application/json:
              example: |
                {
                  "data": null,
                  "success": false,
                  "status": 404
                }
        401:
          body:
            application/json:
              example: |
                {
                  "data": null,
                  "success": false,
                  "status": 401
                }
